produtcs = [
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 2],
  ['Produto', 5.9, 'Praesent finibus ipsum faucibus ornare ornare. Mauris id nisi vel ligula vehicula suscipit. In ac purus dolor. Nullam ac tortor eget ipsum pretium sagittis et a ipsum. Praesent placerat vehicula purus, at ullamcorper velit pretium ut. Praesent nec interdum felis. Cras hendrerit nisi id sagittis tempor.', 1],
]
i = 1
produtcs.each{|product, price, description, category|
  Product.create(name: "#{product}_#{i}", active: true, price: price, description: description, category_id: category )
  i+=i;
}
